apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-app-pipelinerun-
spec:
  serviceAccountName: tekton-sa
  params:
    - name: source-code-repo
      value: https://github.com/cloud-native-garage-method-cohort/dale-lane-buildah-assignment
    - name: deployment-name
      value: express-app
    - name: deployment-namespace
      value: "$(context.pipelineRun.namespace)"
    - name: docker-image
      value: quay.io/dale-lane/express-dale-lane
  pipelineRef:
    name: express-app-pipeline
  workspaces:
    - name: pipeline-shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
