apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: express-app
  app.kubernetes.io/instance: express-app-instance
  app.kubernetes.io/name: express-app
images:
- name: quay.io/dale-lane/express-dale-lane
  newTag: 4e4a02878c6f9c1a5b9c893c69179b5408f8cdec
